import os
import yaml
from collections import OrderedDict

# Directory where your projects are located
projects_directory = "/path/to/projects"

# Content to add inside existing blocks
content_to_add = """
include:
  - project: zzz
    file: zzz

variables:
  nexus_iq_scan_path: .
  nexus_scan_stage: release

stages: 
  - nexusiq-scan
"""

# Define the blocks to update
blocks_to_update = ['variables', 'stages', 'include']

# Iterate through each project directory
for project_dir in os.listdir(projects_directory):
    project_path = os.path.join(projects_directory, project_dir)
    gitlab_ci_file = os.path.join(project_path, ".gitlab-ci.yml")

    # Check if .gitlab-ci.yml exists in the project directory
    if os.path.isfile(gitlab_ci_file):
        with open(gitlab_ci_file, 'r+') as file:
            try:
                # Load the YAML content as an OrderedDict to preserve the order of keys
                ci_content = yaml.safe_load(file)
                if ci_content is None:
                    ci_content = OrderedDict()
            except yaml.YAMLError as exc:
                print(f"Error reading YAML file in project {project_dir}: {exc}")
                continue
            
            # Update each block
            for block in blocks_to_update:
                new_block_content = yaml.safe_load(content_to_add)[block]
                existing_block = ci_content.get(block, OrderedDict())
                
                # Merge new_block_content into existing_block
                for item in new_block_content:
                    if item not in existing_block:
                        existing_block[item] = new_block_content[item]
                
                ci_content[block] = existing_block

            # Reset file pointer to beginning and truncate the file
            file.seek(0)
            file.truncate()

            # Write updated content back to the .gitlab-ci.yml file
            yaml.dump(ci_content, file, default_flow_style=False)
            print(f"Updated .gitlab-ci.yml in project {project_dir}")
    else:
        print(f".gitlab-ci.yml not found in project {project_dir}")
